/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1p2_haroldcamas;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author harol
 */
public class Fifa extends javax.swing.JFrame {

    /**
     * Creates new form Fifa
     */
    public Fifa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_AgregarEquipo = new javax.swing.JPanel();
        lb_nombreEquipo = new javax.swing.JLabel();
        lb_pais = new javax.swing.JLabel();
        Tx_nombreEquipo = new javax.swing.JTextField();
        Tx_pais = new javax.swing.JTextField();
        bt_agregarEquipo = new javax.swing.JButton();
        jp_agregarJugador = new javax.swing.JPanel();
        lb_nombreJugador = new javax.swing.JLabel();
        lb_edad = new javax.swing.JLabel();
        lb_nacionalidad = new javax.swing.JLabel();
        lb_pieHabil = new javax.swing.JLabel();
        Tx_nombreJugador = new javax.swing.JTextField();
        Tx_nacionalidad = new javax.swing.JTextField();
        cb_pieHabil = new javax.swing.JComboBox<>();
        lb_equipoJugador = new javax.swing.JLabel();
        cb_equipos = new javax.swing.JComboBox<>();
        bt_agregarJugador = new javax.swing.JButton();
        lb_posicion = new javax.swing.JLabel();
        cb_posicion = new javax.swing.JComboBox<>();
        FTx_edad = new javax.swing.JTextField();
        jp_agregarEstadio = new javax.swing.JPanel();
        lb_nombreEstadio = new javax.swing.JLabel();
        lb_ciudad = new javax.swing.JLabel();
        lb_capacidad = new javax.swing.JLabel();
        lb_equipoEstadio = new javax.swing.JLabel();
        Tx_nombreEstadio = new javax.swing.JTextField();
        Tx_ciudad = new javax.swing.JTextField();
        Tx_capacidad = new javax.swing.JTextField();
        cb_equiposEstadio = new javax.swing.JComboBox<>();
        bt_agregarEstadio = new javax.swing.JButton();
        jp_Listar = new javax.swing.JPanel();
        cb_tiposListar = new javax.swing.JComboBox<>();
        lb_tipo = new javax.swing.JLabel();
        bt_listar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxA_lista = new javax.swing.JTextArea();
        jp_Modificar = new javax.swing.JPanel();
        lb_tipoM = new javax.swing.JLabel();
        lb_cualM = new javax.swing.JLabel();
        cb_tipoModificar = new javax.swing.JComboBox<>();
        cb_cualModificar = new javax.swing.JComboBox<>();
        bt_Modificar = new javax.swing.JButton();
        jp_Eliminar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_tipoEliminar = new javax.swing.JComboBox<>();
        cb_cualEliminar = new javax.swing.JComboBox<>();
        bt_eliminar = new javax.swing.JButton();
        jp_Simulacion = new javax.swing.JPanel();
        lb_equipo1 = new javax.swing.JLabel();
        lb_equipo2 = new javax.swing.JLabel();
        cb_equipoS1 = new javax.swing.JComboBox<>();
        cb_equipoS2 = new javax.swing.JComboBox<>();
        bt_simulacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        lb_nombreEquipo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_nombreEquipo.setText("Nombre del Equipo");
        lb_nombreEquipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_pais.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_pais.setText("Pais de Origen");
        lb_pais.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tx_nombreEquipo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        Tx_pais.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        bt_agregarEquipo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        bt_agregarEquipo.setText("Agregar Equipo");
        bt_agregarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarEquipoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_AgregarEquipoLayout = new javax.swing.GroupLayout(jp_AgregarEquipo);
        jp_AgregarEquipo.setLayout(jp_AgregarEquipoLayout);
        jp_AgregarEquipoLayout.setHorizontalGroup(
            jp_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_AgregarEquipoLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(jp_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_pais)
                    .addComponent(lb_nombreEquipo))
                .addGap(72, 72, 72)
                .addGroup(jp_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tx_pais)
                    .addGroup(jp_AgregarEquipoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Tx_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(155, 155, 155))
            .addGroup(jp_AgregarEquipoLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(bt_agregarEquipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_AgregarEquipoLayout.setVerticalGroup(
            jp_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_AgregarEquipoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jp_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombreEquipo)
                    .addComponent(Tx_nombreEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jp_AgregarEquipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pais)
                    .addComponent(Tx_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addComponent(bt_agregarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Equipo", jp_AgregarEquipo);

        lb_nombreJugador.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_nombreJugador.setText("Nombre");
        lb_nombreJugador.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_edad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_edad.setText("Edad");
        lb_edad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_nacionalidad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_nacionalidad.setText("Nacionalidad");
        lb_nacionalidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_pieHabil.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_pieHabil.setText("Pie Habil");
        lb_pieHabil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cb_pieHabil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Derecho", "Izquierdo" }));

        lb_equipoJugador.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_equipoJugador.setText("Equipo");
        lb_equipoJugador.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bt_agregarJugador.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bt_agregarJugador.setText("Agregar Jugador");
        bt_agregarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarJugadorMouseClicked(evt);
            }
        });

        lb_posicion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_posicion.setText("Posicion");
        lb_posicion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cb_posicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Medio Campo", "Delantero" }));

        javax.swing.GroupLayout jp_agregarJugadorLayout = new javax.swing.GroupLayout(jp_agregarJugador);
        jp_agregarJugador.setLayout(jp_agregarJugadorLayout);
        jp_agregarJugadorLayout.setHorizontalGroup(
            jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarJugadorLayout.createSequentialGroup()
                .addGroup(jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_agregarJugadorLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_equipoJugador)
                            .addComponent(lb_pieHabil)
                            .addComponent(lb_nacionalidad)
                            .addComponent(lb_edad)
                            .addComponent(lb_nombreJugador)
                            .addComponent(lb_posicion))
                        .addGap(130, 130, 130)
                        .addGroup(jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_posicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Tx_nombreJugador)
                            .addComponent(Tx_nacionalidad)
                            .addComponent(FTx_edad)
                            .addComponent(cb_equipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_pieHabil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jp_agregarJugadorLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(bt_agregarJugador)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jp_agregarJugadorLayout.setVerticalGroup(
            jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarJugadorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombreJugador)
                    .addComponent(Tx_nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_edad)
                    .addComponent(FTx_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nacionalidad)
                    .addComponent(Tx_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_pieHabil)
                    .addComponent(cb_pieHabil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_equipoJugador)
                    .addComponent(cb_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_agregarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_posicion)
                    .addComponent(cb_posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(bt_agregarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Agregar Jugador", jp_agregarJugador);

        lb_nombreEstadio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_nombreEstadio.setText("Nombre");
        lb_nombreEstadio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_ciudad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_ciudad.setText("Ciudad");
        lb_ciudad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_capacidad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_capacidad.setText("Capacidad");
        lb_capacidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lb_equipoEstadio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_equipoEstadio.setText("Equipo ");
        lb_equipoEstadio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bt_agregarEstadio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bt_agregarEstadio.setText("Agregar Estadio");
        bt_agregarEstadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarEstadioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_agregarEstadioLayout = new javax.swing.GroupLayout(jp_agregarEstadio);
        jp_agregarEstadio.setLayout(jp_agregarEstadioLayout);
        jp_agregarEstadioLayout.setHorizontalGroup(
            jp_agregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarEstadioLayout.createSequentialGroup()
                .addGroup(jp_agregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_agregarEstadioLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jp_agregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_equipoEstadio)
                            .addComponent(lb_capacidad)
                            .addComponent(lb_ciudad)
                            .addComponent(lb_nombreEstadio))
                        .addGap(86, 86, 86)
                        .addGroup(jp_agregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tx_capacidad)
                            .addComponent(Tx_nombreEstadio)
                            .addComponent(cb_equiposEstadio, 0, 100, Short.MAX_VALUE)
                            .addComponent(Tx_ciudad, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jp_agregarEstadioLayout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(bt_agregarEstadio)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jp_agregarEstadioLayout.setVerticalGroup(
            jp_agregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_agregarEstadioLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jp_agregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nombreEstadio)
                    .addComponent(Tx_nombreEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_agregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_ciudad)
                    .addComponent(Tx_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_agregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_capacidad)
                    .addComponent(Tx_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_agregarEstadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_equipoEstadio)
                    .addComponent(cb_equiposEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(bt_agregarEstadio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar Estadio", jp_agregarEstadio);

        cb_tiposListar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugadores", "Equipos", "Estadios" }));

        lb_tipo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lb_tipo.setText("Tipo a Listar:");
        lb_tipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bt_listar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        bt_listar.setText("Listar");
        bt_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_listarMouseClicked(evt);
            }
        });

        TxA_lista.setColumns(20);
        TxA_lista.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        TxA_lista.setRows(5);
        jScrollPane1.setViewportView(TxA_lista);

        javax.swing.GroupLayout jp_ListarLayout = new javax.swing.GroupLayout(jp_Listar);
        jp_Listar.setLayout(jp_ListarLayout);
        jp_ListarLayout.setHorizontalGroup(
            jp_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_ListarLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(jp_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jp_ListarLayout.createSequentialGroup()
                        .addComponent(lb_tipo)
                        .addGap(98, 98, 98)
                        .addComponent(cb_tiposListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(193, 193, 193))
            .addGroup(jp_ListarLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(bt_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_ListarLayout.setVerticalGroup(
            jp_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ListarLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jp_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_tiposListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tipo))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(bt_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jp_Listar);

        lb_tipoM.setText("Tipo a modificar");

        lb_cualM.setText("Cual modificar");

        cb_tipoModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugadores", "Equipos", "Estadios" }));
        cb_tipoModificar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoModificarItemStateChanged(evt);
            }
        });

        bt_Modificar.setText("Modificar");
        bt_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_ModificarLayout = new javax.swing.GroupLayout(jp_Modificar);
        jp_Modificar.setLayout(jp_ModificarLayout);
        jp_ModificarLayout.setHorizontalGroup(
            jp_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ModificarLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(jp_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_cualM)
                    .addComponent(lb_tipoM))
                .addGap(73, 73, 73)
                .addGroup(jp_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_tipoModificar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cb_cualModificar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_ModificarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        jp_ModificarLayout.setVerticalGroup(
            jp_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_ModificarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jp_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tipoM)
                    .addComponent(cb_tipoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_cualM)
                    .addComponent(cb_cualModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(bt_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modificar", jp_Modificar);

        jLabel1.setText("Tipo a Eliminar");

        jLabel2.setText("Cual Eliminar");

        cb_tipoEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugadores", "Equipos", "Estadios" }));
        cb_tipoEliminar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tipoEliminarItemStateChanged(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_EliminarLayout = new javax.swing.GroupLayout(jp_Eliminar);
        jp_Eliminar.setLayout(jp_EliminarLayout);
        jp_EliminarLayout.setHorizontalGroup(
            jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_EliminarLayout.createSequentialGroup()
                .addGroup(jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_EliminarLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(115, 115, 115)
                        .addGroup(jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_tipoEliminar, 0, 129, Short.MAX_VALUE)
                            .addComponent(cb_cualEliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jp_EliminarLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jp_EliminarLayout.setVerticalGroup(
            jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_EliminarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_tipoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_cualEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(78, 78, 78)
                .addComponent(bt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar", jp_Eliminar);

        lb_equipo1.setText("Equipo 1:");

        lb_equipo2.setText("Equipo 2:");

        cb_equipoS1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_equipoS1ItemStateChanged(evt);
            }
        });

        bt_simulacion.setText("Simular Partido");
        bt_simulacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_simulacionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_SimulacionLayout = new javax.swing.GroupLayout(jp_Simulacion);
        jp_Simulacion.setLayout(jp_SimulacionLayout);
        jp_SimulacionLayout.setHorizontalGroup(
            jp_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_SimulacionLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addGroup(jp_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp_SimulacionLayout.createSequentialGroup()
                        .addComponent(lb_equipo2)
                        .addGap(84, 84, 84)
                        .addComponent(cb_equipoS2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jp_SimulacionLayout.createSequentialGroup()
                        .addComponent(lb_equipo1)
                        .addGap(84, 84, 84)
                        .addComponent(cb_equipoS1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_SimulacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );
        jp_SimulacionLayout.setVerticalGroup(
            jp_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_SimulacionLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jp_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_equipo1)
                    .addComponent(cb_equipoS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_equipo2)
                    .addComponent(cb_equipoS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(bt_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simulacion", jp_Simulacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_agregarEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarEquipoMouseClicked
        if(Tx_nombreEquipo.getText().equals("") || Tx_pais.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe de llenar todas las casillas primero!");
        }
        else{
            Equipo q = new Equipo(Tx_nombreEquipo.getText(), Tx_pais.getText(), 0);
            Tx_nombreEquipo.setText("");
            Tx_pais.setText("");
            JOptionPane.showMessageDialog(this, "Equipo agregado exitosamente");
            modeloEquipos = (DefaultComboBoxModel) cb_equipos.getModel();
            modeloEquipos.addElement(q);
            cb_equipos.setModel(modeloEquipos);
            cb_equiposEstadio.setModel(modeloEquipos);
            equipos.add(q);
        }
    }//GEN-LAST:event_bt_agregarEquipoMouseClicked

    private void bt_agregarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarJugadorMouseClicked
        if(Tx_nombreJugador.getText().equals("") || Tx_nacionalidad.getText().equals("") || cb_equipos.getSelectedIndex() == -1 || FTx_edad.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe de llenar todas las casillas!");
        }
        
        else if(((Equipo) cb_equipos.getSelectedItem()).getPlantilla().size() == 4){
            JOptionPane.showMessageDialog(this, "El equipo seleccionado ya tiene 4 jugadores!");
        }
        
        else{
            if(cb_posicion.getSelectedItem().equals("Portero")){
                Jugador j = new Portero(Tx_nombreJugador.getText(), Integer.parseInt(FTx_edad.getText()), Tx_nacionalidad.getText(),(String) cb_pieHabil.getSelectedItem(),(Equipo) cb_equipos.getSelectedItem());
                j = j.Propias(j);
                j = j.noPropias(j);
                j.setRating(j.calcularRating());
                ((Equipo) cb_equipos.getSelectedItem()).getPlantilla().add(j);
                ((Equipo) cb_equipos.getSelectedItem()).setRating(((Equipo) cb_equipos.getSelectedItem()).promedioRatings());
                jugadores.add(j);
            }
            else if(cb_posicion.getSelectedItem().equals("Defensa")){
                Jugador j = new Defensa(Tx_nombreJugador.getText(), Integer.parseInt(FTx_edad.getText()), Tx_nacionalidad.getText(),(String) cb_pieHabil.getSelectedItem(),(Equipo) cb_equipos.getSelectedItem());
                j = j.Propias(j);
                j = j.noPropias(j);
                j.setRating(j.calcularRating());
                ((Equipo) cb_equipos.getSelectedItem()).getPlantilla().add(j);
                ((Equipo) cb_equipos.getSelectedItem()).setRating(((Equipo) cb_equipos.getSelectedItem()).promedioRatings());
                jugadores.add(j);
            }
            
            else if(cb_posicion.getSelectedItem().equals("Medio Campo")){
                Jugador j = new MedioCampo(Tx_nombreJugador.getText(), Integer.parseInt(FTx_edad.getText()), Tx_nacionalidad.getText(),(String) cb_pieHabil.getSelectedItem(),(Equipo) cb_equipos.getSelectedItem());
                j = j.Propias(j);
                j = j.noPropias(j);
                j.setRating(j.calcularRating());
                ((Equipo) cb_equipos.getSelectedItem()).getPlantilla().add(j);
                ((Equipo) cb_equipos.getSelectedItem()).setRating(((Equipo) cb_equipos.getSelectedItem()).promedioRatings());
                jugadores.add(j);
            }
            
            else if(cb_posicion.getSelectedItem().equals("Delantero")){
                Jugador j = new Delantero(Tx_nombreJugador.getText(), Integer.parseInt(FTx_edad.getText()), Tx_nacionalidad.getText(),(String) cb_pieHabil.getSelectedItem(),(Equipo) cb_equipos.getSelectedItem());
                j = j.Propias(j);
                j = j.noPropias(j);
                j.setRating(j.calcularRating());
                ((Equipo) cb_equipos.getSelectedItem()).getPlantilla().add(j);
                ((Equipo) cb_equipos.getSelectedItem()).setRating(((Equipo) cb_equipos.getSelectedItem()).promedioRatings());
                jugadores.add(j);
            }
            
            Tx_nombreJugador.setText("");
            Tx_nacionalidad.setText("");
            FTx_edad.setText("");
            cb_equipos.setSelectedIndex(-1);
            
            JOptionPane.showMessageDialog(this, "Jugador agregado exitosamente!");
        }
    }//GEN-LAST:event_bt_agregarJugadorMouseClicked

    private void bt_agregarEstadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_agregarEstadioMouseClicked
        if(Tx_nombreEstadio.getText().equals("") || Tx_ciudad.getText().equals("") || Tx_capacidad.getText().equals("") || cb_equiposEstadio.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Debe de llenar todas las casillas!");
        }
        else{
           Estadio st = new Estadio(Tx_nombreEstadio.getText(), Tx_ciudad.getText(), Integer.parseInt(Tx_capacidad.getText()), (Equipo) cb_equiposEstadio.getSelectedItem());
           Tx_nombreEstadio.setText("");
           Tx_ciudad.setText("");
           Tx_capacidad.setText("");
           cb_equiposEstadio.setSelectedIndex(-1);
           estadios.add(st);
           JOptionPane.showMessageDialog(this, "Estadio agregado exitosamente!");
        }
    }//GEN-LAST:event_bt_agregarEstadioMouseClicked

    private void bt_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_listarMouseClicked
        int cc = 1;
        String lista = "";
        if(cb_tiposListar.getSelectedItem().equals("Jugadores")){
            for (Jugador jugador : jugadores) {
                lista += cc + ".) " + jugador.toString() + " [" + jugador.getRating() + "], " + jugador.getNacionalidad();
                lista += "\n";
                cc++;
            }
        }
        
        else if(cb_tiposListar.getSelectedItem().equals("Equipos")){
            for (Equipo equipo : equipos) {
                lista += cc + ".) " + equipo.toString() + " [" + equipo.getRating() + "], " + equipo.getPais();
                lista += "\n";
                cc++;
            }
        }
        
        else{
            for (Estadio estadio : estadios) {
                lista += cc + ".) " + estadio.toString() + ", " + estadio.getCiudad() + " [" + estadio.getCapacidad() + "] " + "del " + estadio.getEquipo();
                lista += "\n";
                cc++;
            }
        }
        TxA_lista.setText(lista);
    }//GEN-LAST:event_bt_listarMouseClicked

    private void cb_tipoModificarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoModificarItemStateChanged
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_tipoModificar.getModel();
        DefaultComboBoxModel opciones = (DefaultComboBoxModel) cb_cualModificar.getModel();
        String tipo = modelo.getSelectedItem().toString();
        opciones.removeAllElements();
        
        if(tipo.equals("Jugadores")){
            for (Jugador j : jugadores) {
                opciones.addElement(j);
            }
            cb_cualModificar.setModel(opciones);
        }
        else if(tipo.equals("Equipos")){
            for (Equipo q : equipos) {
                opciones.addElement(q);
            }
            cb_cualModificar.setModel(opciones);
        }
        else{
            for (Estadio st : estadios) {
                opciones.addElement(st);
            }
            cb_cualModificar.setModel(opciones);
        }
    }//GEN-LAST:event_cb_tipoModificarItemStateChanged

    private void bt_ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ModificarMouseClicked
        if(cb_cualModificar.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Tiene que elegir cual modificar!");
        }
        else{
            if(cb_cualModificar.getSelectedItem() instanceof Jugador){
                String nombre = JOptionPane.showInputDialog("Elija el nuevo nombre del jugador:");
                int edad = Integer.parseInt(JOptionPane.showInputDialog("Elija la nueva edad del jugador:"));
                String nacionalidad = JOptionPane.showInputDialog("Elija la nueva nacionalidad del jugador:");
                int op = Integer.parseInt(JOptionPane.showInputDialog("Cual es su pierna habil?\n1.)Derecha\n2.)Izquierda"));
                while(op < 1 || op > 2){
                    op = Integer.parseInt(JOptionPane.showInputDialog("Cual es su pierna habil?\n1.)Derecha\n2.)Izquierda"));
                }
                ((Jugador) cb_cualModificar.getSelectedItem()).setNombre(nombre);
                ((Jugador) cb_cualModificar.getSelectedItem()).setEdad(edad);
                ((Jugador) cb_cualModificar.getSelectedItem()).setNacionalidad(nacionalidad);
                if(op == 1){
                    ((Jugador) cb_cualModificar.getSelectedItem()).setPieHabil("Derecha");
                }
                else{
                    ((Jugador) cb_cualModificar.getSelectedItem()).setPieHabil("Izquierda");
                }
            }
            
            else if(cb_cualModificar.getSelectedItem() instanceof Equipo){
                String nombre = JOptionPane.showInputDialog("Elija el nuevo nombre del equipo:");
                String pais = JOptionPane.showInputDialog("Elija el nuevo pais del equipo:");
                ((Equipo) cb_cualModificar.getSelectedItem()).setNombre(nombre);
                ((Equipo) cb_cualModificar.getSelectedItem()).setPais(pais);
            }
            
            else{
                String nombre = JOptionPane.showInputDialog("Elija el nuevo nombre del estadio:");
                String ciudad = JOptionPane.showInputDialog("Elija la nueva ciudad del estadio:");
                int capacidad = Integer.parseInt(JOptionPane.showInputDialog("Elija la nueva capacidad del estadio"));
                ((Estadio) cb_cualModificar.getSelectedItem()).setNombre(nombre);
                ((Estadio) cb_cualModificar.getSelectedItem()).setCiudad(ciudad);
                ((Estadio) cb_cualModificar.getSelectedItem()).setCapacidad(capacidad);
            }
            
            JOptionPane.showMessageDialog(this, "Modificado con exito!");
        }
    }//GEN-LAST:event_bt_ModificarMouseClicked

    private void cb_tipoEliminarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tipoEliminarItemStateChanged
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_tipoEliminar.getModel();
        DefaultComboBoxModel opciones = (DefaultComboBoxModel) cb_cualEliminar.getModel();
        String tipo = modelo.getSelectedItem().toString();
        opciones.removeAllElements();
        
        if(tipo.equals("Jugadores")){
            for (Jugador j : jugadores) {
                opciones.addElement(j);
            }
            cb_cualEliminar.setModel(opciones);
        }
        else if(tipo.equals("Equipos")){
            for (Equipo q : equipos) {
                opciones.addElement(q);
            }
            cb_cualEliminar.setModel(opciones);
        }
        else{
            for (Estadio st : estadios) {
                opciones.addElement(st);
            }
            cb_cualEliminar.setModel(opciones);
        }
    }//GEN-LAST:event_cb_tipoEliminarItemStateChanged

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_eliminarMouseClicked
        if(cb_cualEliminar.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Tiene que elegir cual eliminar!");
        }
        else{
            if(cb_cualEliminar.getSelectedItem() instanceof Jugador){
                jugadores.remove(cb_cualEliminar.getSelectedItem());    
            }
            else if(cb_cualEliminar.getSelectedItem() instanceof Equipo){
                equipos.remove(cb_cualEliminar.getSelectedItem());
                ((DefaultComboBoxModel) cb_equipos.getModel()).removeElement(cb_cualEliminar.getSelectedItem());
                ((DefaultComboBoxModel) cb_equiposEstadio.getModel()).removeElement(cb_cualEliminar.getSelectedItem());
            }
            else{
                estadios.remove(cb_cualEliminar.getSelectedItem());
            }
            cb_cualEliminar.removeAllItems();
            JOptionPane.showMessageDialog(this, "Eliminado con exito!");
        }
    }//GEN-LAST:event_bt_eliminarMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        DefaultComboBoxModel equip = (DefaultComboBoxModel) cb_equipoS1.getModel(); 
        cb_equipoS1.removeAllItems();
        for (Equipo q : equipos) {
            equip.addElement(q);
        }
        cb_equipoS1.setModel(equip);
        if(equipos.size() > 1){
            cb_equipoS1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void cb_equipoS1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_equipoS1ItemStateChanged
        DefaultComboBoxModel equip2 = (DefaultComboBoxModel) cb_equipoS2.getModel();
        cb_equipoS2.removeAllItems();
        for (Equipo q : equipos) {
            if(cb_equipoS1.getSelectedItem() != null){
                if(!cb_equipoS1.getSelectedItem().equals(q)){
                    equip2.addElement(q);
                }
            } 
        }
        cb_equipoS2.setModel(equip2);
    }//GEN-LAST:event_cb_equipoS1ItemStateChanged

    private void bt_simulacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_simulacionMouseClicked
        if(cb_equipoS1.getSelectedIndex() == -1 || cb_equipoS2.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Tiene que elegir 2 equipos!");
        }
        else if (((Equipo) cb_equipoS1.getSelectedItem()).getPlantilla().size() != 4 || ((Equipo) cb_equipoS2.getSelectedItem()).getPlantilla().size() != 4){
            JOptionPane.showMessageDialog(this, "Ambos equipos tienen que tener 4 jugadores!");
        }
        else{
            Random rand = new Random();
            int golesQ1 = 0;
            int golesQ2 = 0;
            double menor = 0;
            double mayor = 0;
            Equipo q1 = (Equipo) cb_equipoS1.getSelectedItem();
            Equipo q2 = (Equipo) cb_equipoS2.getSelectedItem();
            
            if(q1.getRating() > q2.getRating()){
                double probabilidad = q1.getRating() - q2.getRating();
                if(probabilidad <= 10){
                    probabilidad *= 4;
                    menor = probabilidad;
                    mayor = 100 - menor;
                    
                    int random = rand.nextInt(5);
                    for (int i = 1; i <= random; i++) {
                        int rng = rand.nextInt(100) + 1;
                        if(rng < menor + 1){
                            golesQ2++;
                        }
                        else{
                            golesQ1++;
                        }
                    }
                }
                else{
                    probabilidad *= 5;
                    mayor = probabilidad;
                    menor = 100 - mayor;
                    
                    int random = rand.nextInt(10);
                    for (int i = 1; i <= random; i++){
                        int rng = rand.nextInt(100) + 1;
                        if(rng < menor + 1){
                            golesQ2++;
                        }
                        else{
                            golesQ1++;
                        }
                    }
                } 
            }
            else{
                double probabilidad = q2.getRating() - q1.getRating();
                if(probabilidad <= 10){
                    probabilidad *= 4;
                    menor = probabilidad;
                    mayor = 100 - menor;
                    
                    int random = rand.nextInt(5);
                    for (int i = 1; i <= random; i++) {
                        int rng = rand.nextInt(100) + 1;
                        if(rng < menor + 1){
                            golesQ1++;
                        }
                        else{
                            golesQ2++;
                        }
                    }
                }
                else{
                    probabilidad *= 5;
                    mayor = probabilidad;
                    menor = 100 - mayor;
                    
                    int random = rand.nextInt(10);
                    for (int i = 1; i <= random; i++){
                        int rng = rand.nextInt(100) + 1;
                        if(rng < menor + 1){
                            golesQ1++;
                        }
                        else{
                            golesQ2++;
                        }
                    }
                }
            }
            if(golesQ1 > golesQ2){
                JOptionPane.showMessageDialog(this, "El equipo 1: " + q1.getNombre() + " gana con " + golesQ1 + " goles!");
            }
            else if(golesQ2 > golesQ1){
                JOptionPane.showMessageDialog(this, "El equipo 2: " + q2.getNombre() + " gana con " + golesQ2 + " goles!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Es un empate con " + golesQ1 + " goles!!!");
            }
        }
    }//GEN-LAST:event_bt_simulacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fifa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fifa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fifa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fifa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fifa().setVisible(true);
            }
        });
    }
    
    ArrayList<Jugador> jugadores = new ArrayList();
    ArrayList<Equipo> equipos = new ArrayList();
    ArrayList<Estadio> estadios = new ArrayList();
    DefaultComboBoxModel modeloJugadores;
    DefaultComboBoxModel modeloEquipos;
    DefaultComboBoxModel modeloEstadios;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FTx_edad;
    private javax.swing.JTextArea TxA_lista;
    private javax.swing.JTextField Tx_capacidad;
    private javax.swing.JTextField Tx_ciudad;
    private javax.swing.JTextField Tx_nacionalidad;
    private javax.swing.JTextField Tx_nombreEquipo;
    private javax.swing.JTextField Tx_nombreEstadio;
    private javax.swing.JTextField Tx_nombreJugador;
    private javax.swing.JTextField Tx_pais;
    private javax.swing.JButton bt_Modificar;
    private javax.swing.JButton bt_agregarEquipo;
    private javax.swing.JButton bt_agregarEstadio;
    private javax.swing.JButton bt_agregarJugador;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_listar;
    private javax.swing.JButton bt_simulacion;
    private javax.swing.JComboBox<String> cb_cualEliminar;
    private javax.swing.JComboBox<String> cb_cualModificar;
    private javax.swing.JComboBox<String> cb_equipoS1;
    private javax.swing.JComboBox<String> cb_equipoS2;
    private javax.swing.JComboBox<String> cb_equipos;
    private javax.swing.JComboBox<String> cb_equiposEstadio;
    private javax.swing.JComboBox<String> cb_pieHabil;
    private javax.swing.JComboBox<String> cb_posicion;
    private javax.swing.JComboBox<String> cb_tipoEliminar;
    private javax.swing.JComboBox<String> cb_tipoModificar;
    private javax.swing.JComboBox<String> cb_tiposListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jp_AgregarEquipo;
    private javax.swing.JPanel jp_Eliminar;
    private javax.swing.JPanel jp_Listar;
    private javax.swing.JPanel jp_Modificar;
    private javax.swing.JPanel jp_Simulacion;
    private javax.swing.JPanel jp_agregarEstadio;
    private javax.swing.JPanel jp_agregarJugador;
    private javax.swing.JLabel lb_capacidad;
    private javax.swing.JLabel lb_ciudad;
    private javax.swing.JLabel lb_cualM;
    private javax.swing.JLabel lb_edad;
    private javax.swing.JLabel lb_equipo1;
    private javax.swing.JLabel lb_equipo2;
    private javax.swing.JLabel lb_equipoEstadio;
    private javax.swing.JLabel lb_equipoJugador;
    private javax.swing.JLabel lb_nacionalidad;
    private javax.swing.JLabel lb_nombreEquipo;
    private javax.swing.JLabel lb_nombreEstadio;
    private javax.swing.JLabel lb_nombreJugador;
    private javax.swing.JLabel lb_pais;
    private javax.swing.JLabel lb_pieHabil;
    private javax.swing.JLabel lb_posicion;
    private javax.swing.JLabel lb_tipo;
    private javax.swing.JLabel lb_tipoM;
    // End of variables declaration//GEN-END:variables
}
